// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0WyOBBJltia8gp0hDnufUFhUOdNbZQ_w',
    appId: '1:135566623384:web:bdd3be94d7056f214446ed',
    messagingSenderId: '135566623384',
    projectId: 'zumie-98c4c',
    authDomain: 'zumie-98c4c.firebaseapp.com',
    storageBucket: 'zumie-98c4c.appspot.com',
    measurementId: 'G-DP0TTGZ5C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcqVp-1Vp6uFQA_v6l6qMr_TJUvxbVok',
    appId: '1:135566623384:android:bff186f43645bb084446ed',
    messagingSenderId: '135566623384',
    projectId: 'zumie-98c4c',
    storageBucket: 'zumie-98c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-KC3TJhpHkxQtGf_tkMenp6YzJpbPlE',
    appId: '1:135566623384:ios:7e135d1269ef34274446ed',
    messagingSenderId: '135566623384',
    projectId: 'zumie-98c4c',
    storageBucket: 'zumie-98c4c.appspot.com',
    iosClientId:
        '135566623384-9phe4ecqt89p48ojagn9dpqtqk3bbksr.apps.googleusercontent.com',
    iosBundleId: 'com.zumie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS-KC3TJhpHkxQtGf_tkMenp6YzJpbPlE',
    appId: '1:135566623384:ios:840fc84b60044a384446ed',
    messagingSenderId: '135566623384',
    projectId: 'zumie-98c4c',
    storageBucket: 'zumie-98c4c.appspot.com',
    iosClientId:
        '135566623384-f0eneabiroelbf802civf9m1nr75326r.apps.googleusercontent.com',
    iosBundleId: 'com.example.zumie',
  );
}
